# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/ram/ram.xci
# IP: The module: 'ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/ram/ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/ram/ram.xci
# IP: The module: 'ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/ram/ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
