# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/VGAClock/VGAClock.xci
# IP: The module: 'VGAClock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/VGAClock/VGAClock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClock'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/VGAClock/VGAClock.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/VGAClock/VGAClock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/VGAClock/VGAClock.xci
# IP: The module: 'VGAClock' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/VGAClock/VGAClock_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/VGAClock/VGAClock.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/VGAClock/VGAClock_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'VGAClock'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
