# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons.xdc

# IP: ip/ram8/ram8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram8 || ORIG_REF_NAME==ram8} -quiet] -quiet
