# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/source/VIVADOScource/CPU/CPU.cache/wt [current_project]
set_property parent.project_path E:/source/VIVADOScource/CPU/CPU.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/source/VIVADOScource/CPU/CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files c:/Users/wufan/Desktop/data.coe
add_files E:/source/VIVADOScource/CPU/Font.coe
read_verilog -library xil_defaultlib {
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/Define.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/CPURam.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/CPUTop.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/CharStream.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/Control.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/Decode.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/DecodeExecute.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/Division.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/Execute.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/ExecuteMemory.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/Fetch.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/FetchDecode.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/Forwarding.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/HiLo.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/Memory.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/MemoryReceiverAutomation.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/MemoryTransmitter.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/MemoryWriteback.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/Padding.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/RegisterFile.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/StdOutRam.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/TimeDisplay.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/USBReceiver.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/VGADesign.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/VGATop.v
  E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/new/SOC.v
}
read_ip -quiet E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/ram8/ram8.xci
set_property used_in_implementation false [get_files -all e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/ram8/ram8_ooc.xdc]

read_ip -quiet E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/VGAClock/VGAClock.xci
set_property used_in_implementation false [get_files -all e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/VGAClock/VGAClock_board.xdc]
set_property used_in_implementation false [get_files -all e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/VGAClock/VGAClock.xdc]
set_property used_in_implementation false [get_files -all e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/VGAClock/VGAClock_ooc.xdc]

read_ip -quiet E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/FontRom/FontRom.xci
set_property used_in_implementation false [get_files -all e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/FontRom/FontRom_ooc.xdc]

read_ip -quiet E:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/ram/ram.xci
set_property used_in_implementation false [get_files -all e:/source/VIVADOScource/CPU/CPU.srcs/sources_1/ip/ram/ram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/source/VIVADOScource/CPU/CPU.srcs/constrs_1/new/cons.xdc
set_property used_in_implementation false [get_files E:/source/VIVADOScource/CPU/CPU.srcs/constrs_1/new/cons.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top SOC -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef SOC.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file SOC_utilization_synth.rpt -pb SOC_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
